### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by sigxcpu76** [sn4k3/UVtools#378]
## System
 - OS: KDE Neon (Ubuntu 20.04/focal based)
 - Slicer: HALOT BOX
 - Printer: Creality HALOT ONE
 - UVtools version: 2.27.1

```
1. Go to "UVtools -> Help -> About"
2. Right click on "Copy information" -> "Copy the essential information"
3. Paste that infomation bellow this line:

UVtools v2.27.1
Operative system: Linux 5.15.9-051509-generic #202112161611-Ubuntu SMP Thu Dec 16 16:23:18 UTC 2021 X64
Processor: AMD Ryzen 9 5900X 12-Core Processor
Processor cores: 24
Memory RAM: 55.99 / 62.78 GB
Runtime: neon.20.04-x64
Framework: .NET 5.0.13
AvaloniaUI: 0.10.11
OpenCV: 4.5.4-235

Sreens, resolution, working area, usable area:
1: 3840 x 2160 @ 100% (Primary)
    WA: 3762 x 2160    UA: 3762 x 2160

Path: /home/sigxcpu/Downloads/UVtools_linux-x64_v2.27.1

General configuration for OpenCV 4.5.4 =====================================
  Version control:               4.5.4-235-g27567928d7

  Extra modules:
    Location (extra):            /var/lib/buildbot/workers/worker/cv_ubuntu/build/opencv_contrib/modules
    Version control (extra):     4.5.4-61-gc33e5b60

  Platform:
    Timestamp:                   2021-10-26T15:12:54Z
    Host:                        Linux 4.19.104-microsoft-standard x86_64
    CMake:                       3.16.3
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (15 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (30 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (5 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                11
    C++ Compiler:                /usr/bin/c++  (ver 9.3.0)
    C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed  
    Linker flags (Debug):        -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed  
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          /var/lib/buildbot/workers/worker/cv_ubuntu/build/platforms/ubuntu/20.04/build/install/lib/libhdf5.a vtkRenderingOpenGL2 vtkCommonCore vtksys vtkCommonDataModel vtkCommonMath vtkCommonMisc vtkCommonSystem vtkCommonTransforms vtkCommonExecutionModel vtkRenderingCore vtkCommonColor vtkCommonComputationalGeometry vtkFiltersCore vtkFiltersGeneral vtkFiltersGeometry vtkFiltersSources vtkglew vtkInteractionStyle vtkFiltersExtraction vtkFiltersStatistics vtkImagingFourier vtkImagingCore vtkRenderingLOD vtkFiltersModeling vtkIOPLY vtkIOCore vtkdoubleconversion vtklz4 vtklzma vtkzlib vtkFiltersTexture vtkRenderingFreeType vtkfreetype vtkIOExport vtkIOImage vtkDICOMParser vtkmetaio vtkjpeg vtkpng vtktiff vtkIOXML vtkIOXMLParser vtkexpat vtkRenderingContext2D vtkRenderingGL2PSOpenGL2 vtkgl2ps vtkIOGeometry vtkIOLegacy Iconv::Iconv dl m pthread rt
    3rdparty dependencies:       libprotobuf ade ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf zlib quirc ippiw ippicv

  OpenCV modules:
    To be built:                 alphamat aruco barcode bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dnn_superres dpm face features2d flann fuzzy gapi hdf hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab viz wechat_qrcode xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    python2 python3 world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv freetype java julia matlab ovis sfm ts
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         NO

  GUI:                           NONE
    GTK+:                        NO
    VTK support:                 YES (ver 8.2.0)

  Media I/O: 
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 2.1.0-62)
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.2.0)
    JPEG 2000:                   build (ver 2.4.0)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      NO
      avcodec:                   NO
      avformat:                  NO
      avutil:                    NO
      swscale:                   NO
      avresample:                NO
    GStreamer:                   NO
    v4l/v4l2:                    YES (linux/videodev2.h)

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   /var/lib/buildbot/workers/worker/cv_ubuntu/build/platforms/ubuntu/20.04/build/opencv/3rdparty/ippicv/ippicv_lnx/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                /var/lib/buildbot/workers/worker/cv_ubuntu/build/platforms/ubuntu/20.04/build/opencv/3rdparty/ippicv/ippicv_lnx/iw
    VA:                          NO
    Lapack:                      NO
    Eigen:                       YES (ver 3.3.7)
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  OpenCL:                        YES (no extra features)
    Include path:                /var/lib/buildbot/workers/worker/cv_ubuntu/build/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python (for build):            /usr/bin/python2.7

  Install to:                    /var/lib/buildbot/workers/worker/cv_ubuntu/build/platforms/ubuntu/20.04/build/install
-----------------------------------------------------------------


Loaded Assemblies:
001: System.Private.CoreLib, Version=5.0.0.0
002: UVtools, Version=2.27.1.0
003: System.Runtime, Version=5.0.0.0
004: Avalonia.DesktopRuntime, Version=0.10.11.0
005: Avalonia.Controls, Version=0.10.11.0
006: netstandard, Version=2.1.0.0
007: Avalonia.Base, Version=0.10.11.0
008: System.ObjectModel, Version=5.0.0.0
009: Avalonia.Styling, Version=0.10.11.0
010: Avalonia.Input, Version=0.10.11.0
011: Avalonia.Interactivity, Version=0.10.11.0
012: Avalonia.Layout, Version=0.10.11.0
013: Avalonia.Visuals, Version=0.10.11.0
014: Avalonia.Animation, Version=0.10.11.0
015: System.ComponentModel.Primitives, Version=5.0.0.0
016: System.Collections, Version=5.0.0.0
017: System.Console, Version=5.0.0.0
018: UVtools.Core, Version=2.27.1.0
019: System.Drawing.Primitives, Version=5.0.0.0
020: System.IO.FileSystem, Version=5.0.0.0
021: MoreLinq, Version=3.3.2.0
022: System.Data.Common, Version=5.0.0.0
023: System.ComponentModel.TypeConverter, Version=5.0.0.0
024: System.ComponentModel, Version=5.0.0.0
025: System.Xml.ReaderWriter, Version=5.0.0.0
026: System.Private.Xml, Version=5.0.0.0
027: Avalonia.Desktop, Version=0.10.11.0
028: Avalonia.Win32, Version=0.10.11.0
029: Avalonia.MicroCom, Version=0.10.11.0
030: System.Runtime.InteropServices, Version=5.0.0.0
031: System.Collections.Concurrent, Version=5.0.0.0
032: System.Numerics.Vectors, Version=5.0.0.0
033: Avalonia.X11, Version=0.10.11.0
034: Avalonia.Native, Version=0.10.11.0
035: Avalonia.Skia, Version=0.10.11.0
036: System.Runtime.InteropServices.RuntimeInformation, Version=5.0.0.0
037: Avalonia.OpenGL, Version=0.10.11.0
038: System.Reactive, Version=5.0.0.0
039: System.Threading, Version=5.0.0.0
040: System.Private.Uri, Version=5.0.0.0
041: System.Linq, Version=5.0.0.0
042: System.Runtime.Extensions, Version=5.0.0.0
043: System.Xml.XDocument, Version=5.0.0.0
044: System.Private.Xml.Linq, Version=5.0.0.0
045: System.Threading.Thread, Version=5.0.0.0
046: System.Memory, Version=5.0.0.0
047: System.Security.Cryptography.Algorithms, Version=5.0.0.0
048: System.Text.Encoding.Extensions, Version=5.0.0.0
049: Avalonia.FreeDesktop, Version=0.10.11.0
050: Tmds.DBus, Version=0.9.0.0
051: SkiaSharp, Version=2.88.0.0
052: Avalonia.Markup.Xaml, Version=0.10.11.0
053: Avalonia.Themes.Fluent, Version=0.10.11.0
054: Avalonia.Markup, Version=0.10.11.0
055: System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0
056: ThemeEditor.Controls.ColorPicker, Version=0.10.11.0
057: Avalonia.Controls.DataGrid, Version=0.10.11.0
058: MessageBox.Avalonia, Version=1.0.0.0
059: Emgu.CV.Platform.NetStandard, Version=4.5.4.4788
060: System.Xml.XmlSerializer, Version=5.0.0.0
061: System.Diagnostics.TraceSource, Version=5.0.0.0
062: System.Threading.Tasks.Extensions, Version=5.0.0.0
063: System.Buffers, Version=5.0.0.0
064: UVtools.AvaloniaControls, Version=1.0.1.0
065: System.Diagnostics.Process, Version=5.0.0.0
066: System.Linq.Expressions, Version=5.0.0.0
067: System.ComponentModel.Annotations, Version=5.0.0.0
068: System.Reflection.Emit.ILGeneration, Version=5.0.0.0
069: System.Reflection.Primitives, Version=5.0.0.0
070: System.Reflection.Emit.Lightweight, Version=5.0.0.0
071: Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0
072: HarfBuzzSharp, Version=1.0.0.0
073: System.IO.Compression, Version=5.0.0.0
074: System.Net.Http, Version=5.0.0.0
075: System.Text.RegularExpressions, Version=5.0.0.0
076: Newtonsoft.Json, Version=13.0.0.0
077: System.Net.Primitives, Version=5.0.0.0
078: System.Diagnostics.Tracing, Version=5.0.0.0
079: System.Diagnostics.DiagnosticSource, Version=5.0.0.0
080: System.Net.Security, Version=5.0.0.0
081: System.Security.Cryptography.X509Certificates, Version=5.0.0.0
082: System.Net.Sockets, Version=5.0.0.0
083: BinarySerializer, Version=8.6.2.0
084: System.Threading.Tasks, Version=5.0.0.0
085: Microsoft.Win32.Primitives, Version=5.0.0.0
086: System.Text.Encoding, Version=5.0.0.0
087: System.Threading.ThreadPool, Version=5.0.0.0
088: System.IO, Version=5.0.0.0
089: System.Reflection.TypeExtensions, Version=5.0.0.0
090: System.Reflection, Version=5.0.0.0
091: System.Net.NameResolution, Version=5.0.0.0
092: System.Reflection.Extensions, Version=5.0.0.0
093: System.Collections.NonGeneric, Version=5.0.0.0
094: System.IO.Compression.ZipFile, Version=5.0.0.0
095: System.Collections.Specialized, Version=5.0.0.0
096: System.Threading.Tasks.Parallel, Version=5.0.0.0
097: System.Security.Cryptography.Encoding, Version=5.0.0.0
098: System.Formats.Asn1, Version=5.0.0.0
099: System.Runtime.Numerics, Version=5.0.0.0
100: Microsoft.Win32.Registry, Version=6.0.0.0


```

## Describe the bug
Crash when clicking "Issues"

```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Avalonia.X11.X11Window.SetTransparencyLevelHint(WindowTransparencyLevel transparencyLevel) in /_/src/Avalonia.X11/X11Window.cs:line 1160
   at Avalonia.Controls.TopLevel.<>c.<.cctor>b__16_0(TopLevel tl, AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls/TopLevel.cs:line 101
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 756
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 531
   at Avalonia.PropertyStore.ConstantValueEntry`1.RaiseValueChanged(IValueSink sink, IAvaloniaObject owner, AvaloniaProperty property, Optional`1 oldValue, Optional`1 newValue) in /_/src/Avalonia.Base/PropertyStore/ConstantValueEntry.cs:line 75
   at Avalonia.ValueStore.BatchUpdate.End() in /_/src/Avalonia.Base/ValueStore.cs:line 454
   at Avalonia.ValueStore.EndBatchUpdate() in /_/src/Avalonia.Base/ValueStore.cs:line 47
   at Avalonia.StyledElement.DetachStyles() in /_/src/Avalonia.Styling/StyledElement.cs:line 769
   at Avalonia.StyledElement.OnDetachedFromLogicalTreeCore(LogicalTreeAttachmentEventArgs e) in /_/src/Avalonia.Styling/StyledElement.cs:line 694
   at Avalonia.Controls.TopLevel.HandleClosed() in /_/src/Avalonia.Controls/TopLevel.cs:line 368
   at Avalonia.Controls.WindowBase.HandleClosed() in /_/src/Avalonia.Controls/WindowBase.cs:line 202
   at Avalonia.X11.X11Window.Cleanup() in /_/src/Avalonia.X11/X11Window.cs:line 813
   at Avalonia.X11.X11Window.Dispose() in /_/src/Avalonia.X11/X11Window.cs:line 783
   at Avalonia.Controls.Primitives.PopupRoot.Dispose() in /_/src/Avalonia.Controls/Primitives/PopupRoot.cs:line 77
   at Avalonia.Controls.ToolTip.Close() in /_/src/Avalonia.Controls/ToolTip.cs:line 290
   at Avalonia.Controls.ToolTip.IsOpenChanged(AvaloniaPropertyChangedEventArgs e) in /_/src/Avalonia.Controls/ToolTip.cs:line 237
   at System.Reactive.Subjects.Subject`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/Subjects/Subject.cs:line 145
   at Avalonia.AvaloniaObject.RaisePropertyChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 756
   at Avalonia.AvaloniaObject.Avalonia.PropertyStore.IValueSink.ValueChanged[T](AvaloniaPropertyChangedEventArgs`1 change) in /_/src/Avalonia.Base/AvaloniaObject.cs:line 544
   at Avalonia.ValueStore.NotifyValueChanged[T](AvaloniaProperty`1 property, Optional`1 oldValue, BindingValue`1 newValue, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 366
   at Avalonia.ValueStore.SetExisting[T](Object slot, StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 266
   at Avalonia.ValueStore.SetValue[T](StyledPropertyBase`1 property, T value, BindingPriority priority) in /_/src/Avalonia.Base/ValueStore.cs:line 100
   at Avalonia.Controls.ToolTip.SetIsOpen(Control element, Boolean value) in /_/src/Avalonia.Controls/ToolTip.cs:line 121
   at Avalonia.Controls.ToolTipService.Close(Control control) in /_/src/Avalonia.Controls/ToolTipService.cs:line 138
   at Avalonia.Controls.ToolTipService.ControlPointerLeave(Object sender, PointerEventArgs e) in /_/src/Avalonia.Controls/ToolTipService.cs:line 107
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 152
   at Avalonia.Interactivity.EventRoute.RaiseEvent(IInteractive source, RoutedEventArgs e) in /_/src/Avalonia.Interactivity/EventRoute.cs:line 79
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs e) in /_/src/Avalonia.Interactivity/Interactive.cs:line 123
   at Avalonia.Input.MouseDevice.ClearPointerOver(IPointerDevice device, UInt64 timestamp, IInputRoot root, PointerPointProperties properties, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 383
   at Avalonia.Input.MouseDevice.LeaveWindow(IMouseDevice device, UInt64 timestamp, IInputRoot root, PointerPointProperties properties, KeyModifiers inputModifiers) in /_/src/Avalonia.Input/MouseDevice.cs:line 193
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs e) in /_/src/Avalonia.Input/MouseDevice.cs:line 142
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 37
   at Avalonia.X11.X11Window.<ScheduleInput>b__121_0() in /_/src/Avalonia.X11/X11Window.cs:line 743
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.HandleX11(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 169
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 245
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 132
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 187
   at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 47
[1]    3669261 abort (core dumped)  ./UVtools
```

## To Reproduce
1. Open the model
2. Click on 'Issues'

## Expected behavior

No crash.

**Comment by sn4k3** [comment]
Try downgrade to v2.27.0 and reply if it solved

**Comment by sigxcpu76** [comment]
It throws an error when opening the file on 2.27.0

![image](https://user-images.githubusercontent.com/737085/147150752-e935be72-eaad-4f81-ac1b-4a0967327fe2.png)

**Comment by sn4k3** [comment]
> It throws an error when opening the file on 2.27.0
> 
> ![image](https://user-images.githubusercontent.com/737085/147150752-e935be72-eaad-4f81-ac1b-4a0967327fe2.png)

But your printer is Creality HALOT ONE which use .cxdlp, why are you using a .zip file?

**Comment by sigxcpu76** [comment]
You are right. I've prepared the ZIP file to attach on GitHub, but it failed to attach. By mistake, I've picked that one.

Yes, clicking on Issues show the message about "... if they are calculated". No more crash.

**Comment by sn4k3** [comment]
Ok, so keep in that version for now if that work ok. I will try to redirect this problem

**Comment by sigxcpu76** [comment]
Thanks for support.

**Comment by i-hayes** [comment]
I'm having the same problem with or without a file loaded. Tried your suggestion to down grade to 2.27.0 and so far program appears stable and can load and analyse files.

UVtools v2.27.5
Operative system: Linux 5.3.18-59.37-default #1 SMP Mon Nov 22 12:29:04 UTC 2021 (d10168e) X64
Processor: Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz
Processor cores: 8
Memory RAM: 15.78 / 17.56 GB
Runtime: opensuse-leap.15.3-x64
Framework: .NET 5.0.13
AvaloniaUI: 0.10.11
OpenCV: 4.5.4-235

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 100% (Primary)
    WA: 1920 x 1034    UA: 1920 x 1034
2: 1600 x 900 @ 100%
    WA: 1600 x 854    UA: 1600 x 854
3: 1920 x 1080 @ 100%
    WA: 1920 x 1034    UA: 1920 x 1034

Path: /home/ihayes/bin/UVtools_linux-x64

**Comment by sn4k3** [comment]
Can you guys confirm if this is fixed on new release?

**Comment by yaqwsx** [comment]
I just tried 2.27.7 and I did not observe a crash.

**Comment by Lenbok** [comment]
Version 2.27.7 crashes for me still, on Ubuntu 20.04.

**Comment by sn4k3** [comment]
Fixed
