### ISSUE TITLE
[BUG] segfault when trying to open a CTB file

### ISSUE THREAD

**Issue by nonchip** [sn4k3/UVtools#411]
## System
 - OS: void linux (`5.15.12_1 x86_64`; funny you ask that because it's already in the "essential information")
 - Slicer: any (confirmed chitubox and lychee)
 - Printer: creality LD-002H (not that that matters)
 - UVtools version: 2.27.7 (*also* in the "essential information")

```
1. Go to "UVtools -> Help -> About"
2. Right click on "Copy information" -> "Copy the essential information"
3. Paste that infomation bellow this line:
UVtools v2.27.7
Operative system: Linux 5.15.12_1 #1 SMP Wed Dec 29 19:18:57 UTC 2021 X64
Processor: AMD Ryzen 5 2600 Six-Core Processor
Processor cores: 12
Memory RAM: 27.63 / 31.37 GB
Runtime: void-x64
Framework: .NET 5.0.13
AvaloniaUI: 0.10.12
OpenCV: 4.5.5-237

Sreens, resolution, working area, usable area:
1: 1920 x 1200 @ 100% (Primary)
    WA: 1920 x 1168    UA: 1920 x 1168
2: 1680 x 1050 @ 100%
    WA: 1680 x 1050    UA: 1680 x 1050

Path: /home/kyra/bin/UVtools_linux-x64_v2.27.7

General configuration for OpenCV 4.5.5 =====================================
  Version control:               4.5.5-237-gaa8b5d2f70

  Extra modules:
    Location (extra):            /var/lib/buildbot/workers/worker/cv_ubuntu/build/opencv_contrib/modules
    Version control (extra):     4.5.5-62-g7cb6b4d5

  Platform:
    Timestamp:                   2022-01-04T20:38:52Z
    Host:                        Linux 5.10.60.1-microsoft-standard-WSL2 x86_64
    CMake:                       3.16.3
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/make
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (16 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (31 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (5 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                11
    C++ Compiler:                /usr/bin/c++  (ver 9.3.0)
    C++ flags (Release):         -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Werror=return-type -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed  
    Linker flags (Debug):        -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed  
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          /var/lib/buildbot/workers/worker/cv_ubuntu/build/platforms/ubuntu/20.04/build/install/lib/libhdf5.a vtkRenderingOpenGL2 vtkCommonCore vtksys vtkCommonDataModel vtkCommonMath vtkCommonMisc vtkCommonSystem vtkCommonTransforms vtkCommonExecutionModel vtkRenderingCore vtkCommonColor vtkCommonComputationalGeometry vtkFiltersCore vtkFiltersGeneral vtkFiltersGeometry vtkFiltersSources vtkglew vtkInteractionStyle vtkFiltersExtraction vtkFiltersStatistics vtkImagingFourier vtkImagingCore vtkRenderingLOD vtkFiltersModeling vtkIOPLY vtkIOCore vtkdoubleconversion vtklz4 vtklzma vtkzlib vtkFiltersTexture vtkRenderingFreeType vtkfreetype vtkIOExport vtkIOImage vtkDICOMParser vtkmetaio vtkjpeg vtkpng vtktiff vtkIOXML vtkIOXMLParser vtkexpat vtkRenderingContext2D vtkRenderingGL2PSOpenGL2 vtkgl2ps vtkIOGeometry vtkIOLegacy Iconv::Iconv dl m pthread rt
    3rdparty dependencies:       libprotobuf ade ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf zlib quirc ippiw ippicv

  OpenCV modules:
    To be built:                 alphamat aruco barcode bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dnn_superres dpm face features2d flann fuzzy gapi hdf hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking video videoio videostab viz wechat_qrcode xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    python2 python3 world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv freetype java julia matlab ovis sfm ts
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         NO

  GUI:                           NONE
    GTK+:                        NO
    VTK support:                 YES (ver 8.2.0)

  Media I/O: 
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 2.1.2-62)
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.2.0)
    JPEG 2000:                   build (ver 2.4.0)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      NO
      avcodec:                   NO
      avformat:                  NO
      avutil:                    NO
      swscale:                   NO
      avresample:                NO
    GStreamer:                   NO
    v4l/v4l2:                    YES (linux/videodev2.h)

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   /var/lib/buildbot/workers/worker/cv_ubuntu/build/platforms/ubuntu/20.04/build/opencv/3rdparty/ippicv/ippicv_lnx/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                /var/lib/buildbot/workers/worker/cv_ubuntu/build/platforms/ubuntu/20.04/build/opencv/3rdparty/ippicv/ippicv_lnx/iw
    VA:                          NO
    Lapack:                      NO
    Eigen:                       YES (ver 3.3.7)
    Custom HAL:                  NO
    Protobuf:                    build (3.19.1)

  OpenCL:                        YES (no extra features)
    Include path:                /var/lib/buildbot/workers/worker/cv_ubuntu/build/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python (for build):            /usr/bin/python2.7

  Install to:                    /var/lib/buildbot/workers/worker/cv_ubuntu/build/platforms/ubuntu/20.04/build/install
-----------------------------------------------------------------


Loaded Assemblies:
001: System.Private.CoreLib, Version=5.0.0.0
002: UVtools, Version=2.27.7.0
003: System.Runtime, Version=5.0.0.0
004: Avalonia.DesktopRuntime, Version=0.10.12.0
005: Avalonia.Controls, Version=0.10.12.0
006: netstandard, Version=2.1.0.0
007: Avalonia.Base, Version=0.10.12.0
008: System.ObjectModel, Version=5.0.0.0
009: Avalonia.Styling, Version=0.10.12.0
010: Avalonia.Input, Version=0.10.12.0
011: Avalonia.Interactivity, Version=0.10.12.0
012: Avalonia.Layout, Version=0.10.12.0
013: Avalonia.Visuals, Version=0.10.12.0
014: Avalonia.Animation, Version=0.10.12.0
015: System.ComponentModel.Primitives, Version=5.0.0.0
016: System.Collections, Version=5.0.0.0
017: System.Console, Version=5.0.0.0
018: UVtools.Core, Version=2.27.7.0
019: System.Drawing.Primitives, Version=5.0.0.0
020: System.IO.FileSystem, Version=5.0.0.0
021: MoreLinq, Version=3.3.2.0
022: System.Data.Common, Version=5.0.0.0
023: System.ComponentModel.TypeConverter, Version=5.0.0.0
024: System.ComponentModel, Version=5.0.0.0
025: System.Xml.ReaderWriter, Version=5.0.0.0
026: System.Private.Xml, Version=5.0.0.0
027: Avalonia.Desktop, Version=0.10.12.0
028: Avalonia.Win32, Version=0.10.12.0
029: Avalonia.MicroCom, Version=0.10.12.0
030: System.Runtime.InteropServices, Version=5.0.0.0
031: System.Collections.Concurrent, Version=5.0.0.0
032: System.Numerics.Vectors, Version=5.0.0.0
033: Avalonia.X11, Version=0.10.12.0
034: Avalonia.Native, Version=0.10.12.0
035: Avalonia.Skia, Version=0.10.12.0
036: System.Runtime.InteropServices.RuntimeInformation, Version=5.0.0.0
037: Avalonia.OpenGL, Version=0.10.12.0
038: System.Reactive, Version=5.0.0.0
039: System.Threading, Version=5.0.0.0
040: System.Private.Uri, Version=5.0.0.0
041: System.Linq, Version=5.0.0.0
042: System.Runtime.Extensions, Version=5.0.0.0
043: System.Xml.XDocument, Version=5.0.0.0
044: System.Private.Xml.Linq, Version=5.0.0.0
045: System.Threading.Thread, Version=5.0.0.0
046: System.Memory, Version=5.0.0.0
047: System.Security.Cryptography.Algorithms, Version=5.0.0.0
048: System.Text.Encoding.Extensions, Version=5.0.0.0
049: Avalonia.FreeDesktop, Version=0.10.12.0
050: Tmds.DBus, Version=0.9.0.0
051: SkiaSharp, Version=2.88.0.0
052: Avalonia.Markup.Xaml, Version=0.10.12.0
053: Avalonia.Themes.Fluent, Version=0.10.12.0
054: System.Runtime.CompilerServices.Unsafe, Version=5.0.0.0
055: Avalonia.Markup, Version=0.10.12.0
056: ThemeEditor.Controls.ColorPicker, Version=0.10.11.0
057: Avalonia.Controls.DataGrid, Version=0.10.12.0
058: MessageBox.Avalonia, Version=1.0.0.0
059: Emgu.CV.Platform.NetStandard, Version=4.5.5.4823
060: System.Xml.XmlSerializer, Version=5.0.0.0
061: System.Diagnostics.TraceSource, Version=5.0.0.0
062: System.Threading.Tasks.Extensions, Version=5.0.0.0
063: System.Buffers, Version=5.0.0.0
064: UVtools.AvaloniaControls, Version=1.0.1.0
065: System.Linq.Expressions, Version=5.0.0.0
066: System.ComponentModel.Annotations, Version=5.0.0.0
067: System.Reflection.Emit.ILGeneration, Version=5.0.0.0
068: System.Reflection.Primitives, Version=5.0.0.0
069: System.Reflection.Emit.Lightweight, Version=5.0.0.0
070: Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0
071: System.Diagnostics.Process, Version=5.0.0.0
072: HarfBuzzSharp, Version=1.0.0.0
073: System.IO.Compression, Version=5.0.0.0
074: System.Net.Http, Version=5.0.0.0
075: System.Text.RegularExpressions, Version=5.0.0.0
076: Newtonsoft.Json, Version=13.0.0.0
077: System.Net.Primitives, Version=5.0.0.0
078: System.Diagnostics.Tracing, Version=5.0.0.0
079: System.Diagnostics.DiagnosticSource, Version=5.0.0.0
080: System.Net.Security, Version=5.0.0.0
081: System.Security.Cryptography.X509Certificates, Version=5.0.0.0
082: System.Net.Sockets, Version=5.0.0.0
083: Microsoft.Win32.Primitives, Version=5.0.0.0
084: System.Threading.ThreadPool, Version=5.0.0.0
085: System.Net.NameResolution, Version=5.0.0.0
086: BinarySerializer, Version=8.6.2.2
087: System.Threading.Tasks, Version=5.0.0.0
088: System.Text.Encoding, Version=5.0.0.0
089: System.IO, Version=5.0.0.0
090: System.Reflection.TypeExtensions, Version=5.0.0.0
091: System.Reflection, Version=5.0.0.0
092: System.Reflection.Extensions, Version=5.0.0.0
093: System.Collections.NonGeneric, Version=5.0.0.0
094: System.Security.Cryptography.Encoding, Version=5.0.0.0
095: System.Formats.Asn1, Version=5.0.0.0
096: System.Runtime.Numerics, Version=5.0.0.0
097: System.IO.Compression.ZipFile, Version=5.0.0.0
098: System.Collections.Specialized, Version=5.0.0.0
099: System.Threading.Tasks.Parallel, Version=5.0.0.0
100: Microsoft.Win32.Registry, Version=6.0.0.0


```

## Describe the bug
When opening any `.ctb` files, after the loading progressbar is done i see the first layer in the main menu rendered correctly for a split second, followed by a segmentation fault in opencv, without any .net errors

## To Reproduce
1. Open a file
2. Wait for progress dialog to finish
3. See error

## Expected behavior
It not crashing. (issue templates are fun)

## Screenshots
"Full GUI/window screenshot is always a must!" i mean i would but there's no window, it crashed. did i mention issue templates being fun? especially when they both say "delete sections as applicable" and "the impossible thing is always a must"?

## Files
happens with *any* `.ctb` file, from both chitubox and lychee, confirmed loadable on windows.
 
## Exceptions Log file
`errors.log` is empty, but i managed to get *some* info via gdb:

```
Thread 43 ".NET ThreadPool" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff22d1f640 (LWP 29732)]
0x00007fff2a82ebb6 in cv::connectedcomponents::LabelingBolelli4CParallel<int, unsigned char, cv::connectedcomponents::CCStatsOp>::operator()(cv::Mat const&, cv::Mat&, int, cv::connectedcomponents::CCStatsOp&) () from /home/kyra/bin/UVtools_linux-x64_v2.27.7/libcvextern.so
(gdb) bt
#0  0x00007fff2a82ebb6 in cv::connectedcomponents::LabelingBolelli4CParallel<int, unsigned char, cv::connectedcomponents::CCStatsOp>::operator()(cv::Mat const&, cv::Mat&, int, cv::connectedcomponents::CCStatsOp&) () from /home/kyra/bin/UVtools_linux-x64_v2.27.7/libcvextern.so
#1  0x00007fff2a82f695 in int cv::connectedComponents_sub1<cv::connectedcomponents::CCStatsOp>(cv::Mat const&, cv::Mat&, int, int, cv::connectedcomponents::CCStatsOp&) ()
   from /home/kyra/bin/UVtools_linux-x64_v2.27.7/libcvextern.so
#2  0x00007fff2a82f9ad in cv::connectedComponentsWithStats(cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, int, int, int) ()
   from /home/kyra/bin/UVtools_linux-x64_v2.27.7/libcvextern.so
#3  0x00007fff8229b539 in ?? ()
#4  0xffffffffffffffff in ?? ()
#5  0x000000000677e34c in ?? ()
#6  0x00007ffff74b9848 in ?? () from /home/kyra/bin/UVtools_linux-x64_v2.27.7/libcoreclr.so
#7  0x00007fff22d1ebe0 in ?? ()
#8  0x00007fff800bcda0 in ?? ()
#9  0x00007fff800bcda0 in ?? ()
#10 0x00007fff22d1e0c0 in ?? ()
#11 0x00007fff8229b539 in ?? ()
#12 0x00007fff22d1e150 in ?? ()
#13 0x00007fff10003400 in ?? ()
#14 0x00007fff800bcda0 in ?? ()
#15 0x00007fff08008aa0 in ?? ()
#16 0x0000000400000004 in ?? ()
#17 0x00007fff4bcfd588 in ?? ()
#18 0x0000000000000654 in ?? ()
#19 0x00007fff1000e900 in ?? ()
#20 0x00000000000001f8 in ?? ()
#21 0x00007fff499b5200 in ?? ()
#22 0x00007fff22d1e1e0 in ?? ()
#23 0x00007fff8229b242 in ?? ()
#24 0x00000000ffffffff in ?? ()
#25 0x00007fff22d1e160 in ?? ()
#26 0x00007fff100016b0 in ?? ()
#27 0x00007fff10003400 in ?? ()
#28 0x00007fff10003480 in ?? ()
#29 0x00007fff100016f0 in ?? ()
#30 0x000000004bdc7280 in ?? ()
#31 0x00007fff4bdc7388 in ?? ()
#32 0x00007fff4bdc7360 in ?? ()
#33 0x00007fff4bdc7338 in ?? ()
#34 0x00007fff4bdc7310 in ?? ()
#35 0x0000000400000004 in ?? ()
#36 0x00007fff4bdc72e0 in ?? ()
#37 0x00007fff4bdc72b0 in ?? ()
#38 0x00007fff4bdc7280 in ?? ()
#39 0x00007fff4bdc71d8 in ?? ()
#40 0x00007fff22d1e600 in ?? ()
#41 0x00007fff82298813 in ?? ()
#42 0x00000000ffffffff in ?? ()
#43 0x0000000000000002 in ?? ()
#44 0x00007fff8203b788 in ?? ()
#45 0x00007fff82297a90 in ?? ()
#46 0x00007fff22d1e1f0 in ?? ()
#47 0x00007fff8203b788 in ?? ()
#48 0x0000000000000000 in ?? ()
```

**Comment by sn4k3** [comment]
Who says open bug issues aren't fun? 😂
This seen a extension of https://github.com/sn4k3/UVtools/issues/378
Please try to downgrade to v2.27.0 and see if problem happens

**Comment by tescalada** [comment]
Downgrading to v2.27.0 fixed the segfault when opening CTB files for me.
