### ISSUE TITLE
Getting "Repair layers and errors" popup error window when loading *.cbt file Windows 10

### ISSUE THREAD

**Issue by orosalsero1** [sn4k3/UVtools#446]
## System
 - OS: Windows 10 x64
 - Slicer: Chitubox v.1.9.2
 - Printer: QIDI S-box
 - UVtools version: 3.2.1

```
UVtools v3.2.1
Operative system: Microsoft Windows 10.0.19043 X64
Processor: Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz
Processor cores: 4
Memory RAM: 7.15 / 11.90 GB
Runtime: win10-x64
Framework: .NET 6.0.3
AvaloniaUI: 0.10.13
OpenCV: 4.5.5-237

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 100%
    WA: 1920 x 1080    UA: 1920 x 1080
2: 1920 x 1080 @ 100% (Primary) (On this)
    WA: 1920 x 1080    UA: 1920 x 1080

Path: C:\Program Files\UVtools_win-x64_v3.2.1\

General configuration for OpenCV 4.5.5 =====================================
  Version control:               4.5.5-237-gaa8b5d2f70

  Extra modules:
    Location (extra):            D:/bb/cv_x64/build/build_x64/../opencv_contrib/modules
    Version control (extra):     4.5.5-62-g7cb6b4d5

  Platform:
    Timestamp:                   2022-01-05T15:01:30Z
    Host:                        Windows 10.0.22000 AMD64
    CMake:                       3.21.3
    CMake generator:             Visual Studio 16 2019
    CMake build tool:            C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe
    MSVC:                        1929
    Configuration:               Debug Release MinSizeRel RelWithDebInfo

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                11
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe  (ver 19.29.30138.0)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MD /O2 /Ob2 /DNDEBUG 
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MDd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP   /MD /O2 /Ob2 /DNDEBUG 
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP /MDd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /INCREMENTAL:NO 
    Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL 
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          wsock32 comctl32 gdi32 ole32 setupapi ws2_32 D:/bb/cv_x64/build/build_x64/install/lib/freetype.lib D:/bb/cv_x64/build/build_x64/install/lib/harfbuzz.lib D:/bb/cv_x64/build/build_x64/install/lib/libhdf5.lib vtkRenderingOpenGL2 vtkCommonCore vtksys vtkCommonDataModel vtkCommonMath vtkCommonMisc vtkCommonSystem vtkCommonTransforms vtkCommonExecutionModel vtkRenderingCore vtkCommonColor vtkCommonComputationalGeometry vtkFiltersCore vtkFiltersGeneral vtkFiltersGeometry vtkFiltersSources vtkglew vtkInteractionStyle vtkFiltersExtraction vtkFiltersStatistics vtkImagingFourier vtkImagingCore vtkRenderingLOD vtkFiltersModeling vtkIOPLY vtkIOCore vtkdoubleconversion vtklz4 vtklzma vtkzlib vtkFiltersTexture vtkRenderingFreeType vtkfreetype vtkIOExport vtkIOImage vtkDICOMParser vtkmetaio vtkjpeg vtkpng vtktiff vtkIOXML vtkIOXMLParser vtkexpat vtkRenderingContext2D vtkRenderingGL2PSOpenGL2 vtkgl2ps vtkIOGeometry vtkIOLegacy
    3rdparty dependencies:       libprotobuf ade ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf zlib quirc

  OpenCV modules:
    To be built:                 alphamat aruco barcode bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dnn_superres dpm face features2d flann freetype fuzzy gapi hdf hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching text tracking ts video videoio videostab viz wechat_qrcode xfeatures2d ximgproc xobjdetect xphoto
    Disabled:                    python_bindings_generator python_tests world
    Disabled by dependency:      -
    Unavailable:                 cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv java julia matlab ovis python2 python3 sfm
    Applications:                perf_tests
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI:                           WIN32UI
    Win32 UI:                    YES
    VTK support:                 YES (ver 8.2.0)

  Media I/O: 
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 2.1.2-62)
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.2.0)
    JPEG 2000:                   build (ver 2.4.0)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.134.100)
      avformat:                  YES (58.76.100)
      avutil:                    YES (56.70.100)
      swscale:                   YES (5.9.100)
      avresample:                YES (4.0.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:                      YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Eigen:                       YES (ver 3.3.7)
    Custom HAL:                  NO
    Protobuf:                    build (3.19.1)

  OpenCL:                        YES (NVD3D11)
    Include path:                D:/bb/cv_x64/build/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python (for build):            C:/python-virt/python37/python.exe

  Java:                          
    ant:                         NO
    JNI:                         C:/Program Files/Eclipse Foundation/jdk-8.0.302.8-hotspot/include C:/Program Files/Eclipse Foundation/jdk-8.0.302.8-hotspot/include/win32 C:/Program Files/Eclipse Foundation/jdk-8.0.302.8-hotspot/include
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    D:/bb/cv_x64/build/build_x64/install
-----------------------------------------------------------------


Loaded Assemblies:
001: System.Private.CoreLib, Version=6.0.0.0
002: UVtools, Version=3.2.1.0
003: System.Runtime, Version=6.0.0.0
004: Avalonia.Controls, Version=0.10.13.0
005: netstandard, Version=2.1.0.0
006: Avalonia.DesktopRuntime, Version=0.10.13.0
007: Avalonia.Base, Version=0.10.13.0
008: System.ObjectModel, Version=6.0.0.0
009: Avalonia.Styling, Version=0.10.13.0
010: Avalonia.Input, Version=0.10.13.0
011: Avalonia.Interactivity, Version=0.10.13.0
012: Avalonia.Layout, Version=0.10.13.0
013: Avalonia.Visuals, Version=0.10.13.0
014: Avalonia.Animation, Version=0.10.13.0
015: System.ComponentModel.Primitives, Version=6.0.0.0
016: System.Collections, Version=6.0.0.0
017: System.Linq, Version=6.0.0.0
018: UVtools.Core, Version=3.2.1.0
019: System.Drawing.Primitives, Version=6.0.0.0
020: Projektanker.Icons.Avalonia, Version=4.3.0.0
021: Avalonia.Desktop, Version=0.10.13.0
022: Avalonia.Win32, Version=0.10.13.0
023: Avalonia.MicroCom, Version=0.10.13.0
024: System.Collections.Concurrent, Version=6.0.0.0
025: System.Runtime.InteropServices, Version=6.0.0.0
026: System.Numerics.Vectors, Version=6.0.0.0
027: Avalonia.X11, Version=0.10.13.0
028: Avalonia.Native, Version=0.10.13.0
029: System.Runtime.InteropServices.RuntimeInformation, Version=6.0.0.0
030: Avalonia.Skia, Version=0.10.13.0
031: Avalonia.OpenGL, Version=0.10.13.0
032: Projektanker.Icons.Avalonia.FontAwesome, Version=4.3.0.0
033: Projektanker.Icons.Avalonia.MaterialDesign, Version=4.3.0.0
034: System.Reactive, Version=5.0.0.0
035: System.Threading, Version=6.0.0.0
036: System.Private.Uri, Version=6.0.0.0
037: System.ComponentModel, Version=6.0.0.0
038: System.Runtime.Extensions, Version=6.0.0.0
039: System.Xml.XDocument, Version=6.0.0.0
040: System.Private.Xml.Linq, Version=6.0.0.0
041: System.Private.Xml, Version=6.0.0.0
042: System.Memory, Version=6.0.0.0
043: System.Text.Encoding.Extensions, Version=6.0.0.0
044: System.Threading.Thread, Version=6.0.0.0
045: Microsoft.Win32.Primitives, Version=6.0.0.0
046: SkiaSharp, Version=2.88.0.0
047: System.Threading.Timer, Version=6.0.0.0
048: Avalonia.Markup.Xaml, Version=0.10.13.0
049: Avalonia.Themes.Fluent, Version=0.10.13.0
050: System.ComponentModel.TypeConverter, Version=6.0.0.0
051: System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0
052: Avalonia.Markup, Version=0.10.13.0
053: Avalonia.Controls.DataGrid, Version=0.10.13.0
054: ThemeEditor.Controls.ColorPicker, Version=0.10.12.0
055: MessageBox.Avalonia, Version=1.0.0.0
056: System.Xml.XmlSerializer, Version=6.0.0.0
057: System.Collections.NonGeneric, Version=6.0.0.0
058: System.Runtime.Loader, Version=6.0.0.0
059: System.Diagnostics.TraceSource, Version=6.0.0.0
060: System.Text.RegularExpressions, Version=6.0.0.0
061: Emgu.CV.Platform.NetStandard, Version=4.5.5.4823
062: System.Xml.ReaderWriter, Version=6.0.0.0
063: System.Net.Http, Version=6.0.0.0
064: System.Net.Primitives, Version=6.0.0.0
065: System.Reflection.Emit.ILGeneration, Version=6.0.0.0
066: System.Reflection.Emit, Version=6.0.0.0
067: Microsoft.GeneratedCode, Version=1.0.0.0
068: System.Reflection.Primitives, Version=6.0.0.0
069: UVtools.AvaloniaControls, Version=2.0.1.0
070: System.Drawing.Common, Version=4.0.0.0
071: System.Text.Json, Version=6.0.0.0
072: System.Reflection.Emit.Lightweight, Version=6.0.0.0
073: System.Text.Encodings.Web, Version=6.0.0.0
074: System.Runtime.Intrinsics, Version=6.0.0.0
075: System.Linq.Expressions, Version=6.0.0.0
076: System.ComponentModel.Annotations, Version=6.0.0.0
077: Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0
078: System.Buffers, Version=6.0.0.0
079: HarfBuzzSharp, Version=1.0.0.0
080: System.IO.Compression, Version=6.0.0.0
081: System.Diagnostics.Tracing, Version=6.0.0.0
082: System.Diagnostics.DiagnosticSource, Version=6.0.0.0
083: BinarySerializer, Version=8.6.2.2
084: System.Net.Security, Version=6.0.0.0
085: System.Threading.Tasks, Version=6.0.0.0
086: System.Security.Cryptography.X509Certificates, Version=6.0.0.0
087: System.IO, Version=6.0.0.0
088: System.Text.Encoding, Version=6.0.0.0
089: System.Reflection.TypeExtensions, Version=6.0.0.0
090: System.Reflection, Version=6.0.0.0
091: System.Reflection.Extensions, Version=6.0.0.0
092: System.Net.Sockets, Version=6.0.0.0
093: System.IO.Compression.ZipFile, Version=6.0.0.0
094: System.Threading.Overlapped, Version=6.0.0.0
095: System.Net.NameResolution, Version=6.0.0.0
096: System.Threading.ThreadPool, Version=6.0.0.0
097: System.Threading.Tasks.Parallel, Version=6.0.0.0
098: System.Security.Cryptography.Primitives, Version=6.0.0.0
099: System.Security.Principal.Windows, Version=6.0.0.0
100: System.Security.Claims, Version=6.0.0.0
101: System.Security.Cryptography.Encoding, Version=6.0.0.0
102: K4os.Compression.LZ4, Version=1.2.16.0
103: System.IO.FileSystem.DriveInfo, Version=6.0.0.0
104: System.Diagnostics.StackTrace, Version=6.0.0.0
105: System.Reflection.Metadata, Version=6.0.0.0
106: System.Collections.Immutable, Version=6.0.0.0
107: Markdown.Avalonia, Version=0.10.10.0
108: Markdown.Avalonia.SyntaxHigh, Version=0.10.10.0
109: ColorTextBlock.Avalonia, Version=0.10.10.0
110: AvaloniaEdit, Version=0.10.0.0
111: Microsoft.Win32.Registry, Version=6.0.0.0


```

## Describe the bug
I'm loading a *.CBT Chitubox created file for my QIDI S-box resin printer, once the file is loaded the program generates an error when checking the model errors.
## To Reproduce
1. Goto file Open
2. Click on 'file to load'
3. Wait for UVtools to load file
4. See error below received in popup error window:
```
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at UVtools.Core.Operations.OperationRepairLayers.<>c__DisplayClass69_2.<ExecuteInternally>b__7(IGrouping`2 group) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\Operations\OperationRepairLayers.cs:line 322
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
   at UVtools.Core.Operations.OperationRepairLayers.ExecuteInternally(OperationProgress progress) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\Operations\OperationRepairLayers.cs:line 302
   at UVtools.Core.Operations.Operation.Execute(OperationProgress progress) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\Operations\Operation.cs:line 561
   at UVtools.WPF.MainWindow.<>c__DisplayClass115_0.<RunOperation>b__0() in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\MainWindow.axaml.cs:line 2137
 ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at UVtools.Core.Operations.OperationRepairLayers.<>c__DisplayClass69_2.<ExecuteInternally>b__7(IGrouping`2 group) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\Operations\OperationRepairLayers.cs:line 322
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at UVtools.Core.Operations.OperationRepairLayers.<>c__DisplayClass69_2.<ExecuteInternally>b__7(IGrouping`2 group) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\Operations\OperationRepairLayers.cs:line 322
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #3) System.NullReferenceException: Object reference not set to an instance of an object.
   at UVtools.Core.Operations.OperationRepairLayers.<>c__DisplayClass69_2.<ExecuteInternally>b__7(IGrouping`2 group) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\Operations\OperationRepairLayers.cs:line 322
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #4) System.NullReferenceException: Object reference not set to an instance of an object.
   at UVtools.Core.Operations.OperationRepairLayers.<>c__DisplayClass69_2.<ExecuteInternally>b__7(IGrouping`2 group) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\Operations\OperationRepairLayers.cs:line 322
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #5) System.NullReferenceException: Object reference not set to an instance of an object.
   at UVtools.Core.Operations.OperationRepairLayers.<>c__DisplayClass69_2.<ExecuteInternally>b__7(IGrouping`2 group) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\Operations\OperationRepairLayers.cs:line 322
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #6) System.NullReferenceException: Object reference not set to an instance of an object.
   at UVtools.Core.Operations.OperationRepairLayers.<>c__DisplayClass69_2.<ExecuteInternally>b__7(IGrouping`2 group) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\Operations\OperationRepairLayers.cs:line 322
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---

 ---> (Inner Exception #7) System.NullReferenceException: Object reference not set to an instance of an object.
   at UVtools.Core.Operations.OperationRepairLayers.<>c__DisplayClass69_2.<ExecuteInternally>b__7(IGrouping`2 group) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\Operations\OperationRepairLayers.cs:line 322
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
```

## Expected behavior
I close the error window and I choose repair file than nothing the timer starts on file repair but the bar is always at 68%

## A clear and concise description of what you expected to happen.
I expect the bar to move as the file is being fixed but it just stays at 68% for minutes on end.

## Screenshots
![image](https://user-images.githubusercontent.com/20641743/161458046-9158d03f-6888-4122-a495-b5cf0d860d62.png)

## Files

[_JC_head_no_hat-cbt.zip](https://github.com/sn4k3/UVtools/files/8406056/_JC_head_no_hat-cbt.zip)

 
## Exceptions Log file

[UVtools error log.zip](https://github.com/sn4k3/UVtools/files/8406063/UVtools.error.log.zip)

**Comment by sn4k3** [comment]
I think your **Steps To Reproduce** the error are incomplete. 
I can open the file correctly, i also search issues and repair issues without any trouble.
Can you update the steps to the exact steps?

**Comment by sn4k3** [comment]
Fixed
