### ISSUE TITLE
[BUG] Flashforge SGVX error.

### ISSUE THREAD

**Issue by doyundoyun** [sn4k3/UVtools#462]
![image](https://user-images.githubusercontent.com/90031064/163716201-f783e674-0c88-4d08-b325-6ac53a807cab.png)

**Comment by doyundoyun** [comment]
System.IO.FileLoadException: This file does not contain a resolution and/or display size information needed to generate the layer images.
Note that FlashDLPrint slicer is unable to output files with the required information to load in here.
Please use other compatible slicer capable of output the correct information to load the file in here.
File name: 'C:\Users\doyun\OneDrive\Desktop\20mm_Box.svgx'
   at UVtools.Core.FileFormats.FlashForgeSVGXFile.DecodeInternally(OperationProgress progress) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\FileFormats\FlashForgeSVGXFile.cs:line 640
   at UVtools.Core.FileFormats.FileFormat.Decode(String fileFullPath, FileDecodeType fileDecodeType, OperationProgress progress) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.Core\FileFormats\FileFormat.cs:line 3324
   at UVtools.WPF.MainWindow.<>c__DisplayClass104_0.<ProcessFile>b__1() in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\MainWindow.axaml.cs:line 1453

**Comment by doyundoyun** [comment]
http://gofile.me/4zQ31/kh0vSGhGS

Please download and  look into this SVGX file.
