### ISSUE TITLE
[Crash] System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by bethouxa** [sn4k3/UVtools#547]
Hello, this happened immediately upon pressing ctrl-Z after a "repair layers and issues", using the toolbox button in the issues panel, next to the "detect" button. Feel free to ask if you need the file that caused it.

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method851(Closure , Object )
   at Avalonia.Controls.HotKeyManager.HotkeyCommandWrapper.Execute(Object parameter) in /_/src/Avalonia.Controls/HotkeyManager.cs:line 29
   at Avalonia.Input.KeyBinding.TryHandle(KeyEventArgs args) in /_/src/Avalonia.Input/KeyBinding.cs:line 40
   at Avalonia.Input.KeyboardDevice.ProcessRawEvent(RawInputEventArgs e) in /_/src/Avalonia.Input/KeyboardDevice.cs:line 241
   at Avalonia.Input.InputManager.ProcessInput(RawInputEventArgs e) in /_/src/Avalonia.Input/InputManager.cs:line 37
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.AppWndProc.cs:line 541
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/WindowImpl.WndProc.cs:line 33
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 210
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 65
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 120
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 209
   at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 70
Category: Application
File: Guts_75mm_orcA.ctb  [Version: 2] [Class: ChituboxFile]

# System
UVtools v3.6.2 X64
Operative system: Microsoft Windows 10.0.19044 X64
Processor: AMD Ryzen 5 2600 Six-Core Processor            
Processor cores: 12
Memory RAM: 9.64 / 15.94 GB
Runtime: win10-x64
Framework: .NET 6.0.8
AvaloniaUI: 0.10.18
OpenCV: 4.5.5-237

Path:       C:\Program Files (x86)\UVtools\
Executable: C:\Program Files (x86)\UVtools\UVtools.exe


Machine date time: 09/02/2022 02:30:36
    UTC date time: 09/02/2022 00:30:36
```

**Comment by sn4k3** [comment]
This bug was fixed on latest release, please update your UVtools
