### ISSUE TITLE
[Crash] System.TypeInitializationException: The type initializer for 'Avalonia.Win32.Win32Platform' threw an exception.

### ISSUE THREAD

**Issue by DeclanHawke** [sn4k3/UVtools#559]
```
System.TypeInitializationException: The type initializer for 'Avalonia.Win32.Win32Platform' threw an exception.
 ---> System.ComponentModel.Win32Exception (8): Not enough memory resources are available to process this command.
   at Avalonia.Win32.Win32Platform.CreateMessageWindow() in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 303
   at Avalonia.Win32.Win32Platform..ctor() in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 120
   at Avalonia.Win32.Win32Platform..cctor() in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 111
   --- End of inner exception stack trace ---
   at Avalonia.Win32.Win32Platform.Initialize(Win32PlatformOptions options) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 149
   at Avalonia.Win32ApplicationExtensions.<>c__0`1.<UseWin32>b__0_0() in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 32
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 301
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 69
Category: Application
```

# System
UVtools v3.6.6 X64
Operative system: Microsoft Windows 10.0.22000 X64
Processor: AMD Ryzen 7 5800H with Radeon Graphics         
Processor cores: 16
Memory RAM: 12.72 / 15.35 GB
Runtime: win10-x64
Framework: .NET 6.0.9
AvaloniaUI: 0.10.18
OpenCV: 4.5.5-237

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe

Machine date time: 09/21/2022 03:21:15
    UTC date time: 09/21/2022 07:21:15

**Comment by sn4k3** [comment]
The application crashed due the lack of necessary RAM to process something

>  Not enough memory resources are available to process this command.

Maybe you have no pagefile or it was full.
Your Memory RAM: 12.72 / 15.35 GB, after crash, that means before crash with file loaded it was hitting the 15.xx GB. UVtools require a good margin of RAM to process modern files with large layer set. Please consider upgrade to 32GB.
