### ISSUE TITLE
[Crash] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)

### ISSUE THREAD

**Issue by GoPadge** [sn4k3/UVtools#685]
### System

```Text
UVtools v3.12.2 X64
Operative system: Microsoft Windows 10.0.19044 X64
Processor: Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
Processor cores: 4
Memory RAM: 20.65 / 47.96 GB
Runtime: win10-x64
Framework: .NET 6.0.15
AvaloniaUI: 0.10.19
OpenCV: 4.6.0

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
```

### Printer and Slicer

- Printer:  Creality LD-0002R / Creality Ender 5 Pro
- Slicer:  ChituBox / PrusaSlicer / Lychee Slicer / Cura  (It really depends on my mood...)
In this case I was working with a STL file that had been edited in Meshmixer to fix holes, Fusion 360 to add structure to and then the stl had been supported and sliced in ChituBox V1.9.4.

### Description of the bug

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at UVtools.WPF.LayerCache.set_Layer(Layer value) in UVtools.WPF\LayerCache.cs:line 40
   at UVtools.WPF.MainWindow.ShowLayer() in UVtools.WPF\MainWindow.LayerPreview.cs:line 1489
   at UVtools.WPF.MainWindow.ComputeIssues(IssuesDetectionConfiguration config) in UVtools.WPF\MainWindow.Issues.cs:line 688
   at UVtools.WPF.MainWindow.OnClickDetectIssues() in UVtools.WPF\MainWindow.Issues.cs:line 631
   at UVtools.WPF.MainWindow.<set_SelectedTabItem>b__49_0() in UVtools.WPF\MainWindow.axaml.cs:line 205
   --- End of inner exception stack trace ---
Category: Task
File: _Wolf_2_Posted_v1.ctb  [Version: 4] [Class: ChituboxFile]

Machine date time: 3/31/2023 11:42:37 AM
    UTC date time: 3/31/2023 4:42:37 PM
```

### How to reproduce

Eh,  I had been working on one file, saved everything and then dragged in the next file and the system threw up.

**Comment by GoPadge** [comment]
Unfortunately no, I can't replicate it either.

---
Thank you,

Barry Padgett
785-969-8624

On 03/31/2023 12:09, Tiago Conceição wrote:

> This bug was first reported here: #648 [1]
> I can't find a way to reproduce it, can you?
> 
> --
> Reply to this email directly, view it on GitHub [2], or unsubscribe 
> [3].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] https://github.com/sn4k3/UVtools/issues/648
[2] https://github.com/sn4k3/UVtools/issues/685#issuecomment-1492283881
[3]
