### ISSUE TITLE
[Bug] 4.0.1 Crashing frequently on OS X -- System.InvalidOperationException: Collection was modified; enumeration operation may not execute

### ISSUE THREAD

**Issue by veddermatic** [sn4k3/UVtools#762]
### System

```Text
UVtools v4.0.1 Arm64
Operative system: Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 Arm64
Processor: Apple M1 Pro
Processor cores: 8
Memory RAM: 5.48 / 10.10 GB
Runtime: osx.13-arm64
Framework: .NET 6.0.22
AvaloniaUI: 11.0.4
OpenCV: 4.8.0

Sreens, resolution, working area, usable area:
1: 1512 x 982 @ 100% (Primary)
    WA: 1512 x 944    UA: 1512 x 944

Path:       /Applications/UVtools.app/Contents/MacOS/
Executable: /Applications/UVtools.app/Contents/MacOS/UVtools
Loaded file: UVtools_demo_file.sl1 [Version: 0] [Class: SL1File]
```

### Printer and Slicer

- Printer: Mono 4k
- Slicer:  Lychee

### Description of the bug

Since upgrading to 4.0.1 UV Tools crashes more often than not when running issue detection.

```
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at Avalonia.Rendering.Composition.Server.ServerCompositor.NotifyBatchesProcessed()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.RenderCore()
   at Avalonia.Rendering.Composition.Server.ServerCompositor.Render()
   at Avalonia.Media.MediaContext.SyncCommit(Compositor compositor, Boolean waitFullRender)
   at Avalonia.Rendering.Composition.CompositingRenderer.Paint(Rect rect)
   at Avalonia.Controls.TopLevel.HandlePaint(Rect rect)
   at Avalonia.Native.WindowBaseImpl.WindowBaseEvents.Avalonia.Native.Interop.IAvnWindowBaseEvents.Paint()
   at Avalonia.Native.Interop.Impl.__MicroComIAvnWindowBaseEventsVTable.Paint(Void* this)
--- End of stack trace from previous location ---
   at Avalonia.Native.DispatcherImpl.RunLoop(CancellationToken token)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at UVtools.UI.Program.Main(String[] args) in UVtools.UI/Program.cs:line 174
Category: Application
File: troopsModular.pwma  [Version: 516] [Class: PhotonWorkshopFile]

Machine date time: 10/1/2023 10:49:28 AM
    UTC date time: 10/1/2023 2:49:28 PM
```

### How to reproduce

1. Be on OS X 13.5.2
2. Open a .pwma file
3. Detect Issues
4. Cross fingers...... oh, it crashed =(

Seems not to be file dependent. I can open a file, detect, get the crash, then reopen UV Tools, open that file again and have it detect fine.

**Comment by sn4k3** [comment]
This bug is outside UVtools scope, it comes from UI framework. I will report the bug to them.
Please stick with the older version until this is fixed.

**Comment by sn4k3** [comment]
@timunie The last older version it use Avalonia 0.10.21, but even other past version's were ok. This is the first report I saw about this problem.

**Comment by sn4k3** [comment]
@veddermatic Please try this compilation:

1. Download: https://we.tl/t-z24JEydM6s
2. Extract the app to your Desktop
3. Open terminal and run: `codesign --force --deep --sign - $HOME/Desktop/UVtools.app`
4. Open UVtools from desktop, try and report back

For the reference, it was compiled with: ![image](https://github.com/sn4k3/UVtools/assets/113281/718b86c4-1eef-492d-b233-941ff674bb11)

**Comment by sn4k3** [comment]
Should be fixed with new version, please check.
