### ISSUE TITLE
[Crash] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service)

### ISSUE THREAD

**Issue by murphy-freelance** [sn4k3/UVtools#811]
### System

```Text
UVtools v4.0.6 X64
Operative system: Linux 6.6.7-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Dec 13 21:43:37 UTC 2023 X64
Processor: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
Processor cores: 8
Memory RAM: 14.37 / 15.55 GB
Runtime: fedora.39-x64
Framework: .NET 6.0.25
AvaloniaUI: 11.0.6
OpenCV: 4.8.1

Path:       /tmp/.mount_UVtoolguFdrS/usr/bin/
Executable: /tmp/.mount_UVtoolguFdrS/usr/bin/UVtools
```

### Printer and Slicer

- Printer: Mars 4 Max
- Slicer: None

### Description of the bug

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service)
 ---> Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   --- End of inner exception stack trace ---
Category: Task
File: UVtools_demo_file.sl1  [Version: 0] [Class: SL1File]

Machine date time: 25/12/2023 22.32.54
    UTC date time: 25/12/2023 21.32.54
```

### How to reproduce

Open the title bar menu and wait a couple of seconds before it automatically crashes

**Comment by murphy-freelance** [comment]
Just saw this is a duplicate sorry for the trouble
