### ISSUE TITLE
[Crash] Dbus related error on opening .goo file from Lychee

### ISSUE THREAD

**Issue by keyz182** [sn4k3/UVtools#824]
### System

```Text
UVtools v4.0.6 X64
Operative system: Linux 6.6.9-200.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Jan  1 20:05:54 UTC 2024 X64
Processor: AMD Ryzen 9 7900X 12-Core Processor
Processor cores: 24
Memory RAM: 31.92 / 62.52 GB
Runtime: fedora.39-x64
Framework: .NET 6.0.25
AvaloniaUI: 11.0.6
OpenCV: 4.8.1

Path:       /tmp/.mount_UVtoolZC0FuY/usr/bin/
Executable: /tmp/.mount_UVtoolZC0FuY/usr/bin/UVtools
```

### Printer and Slicer

- Printer: Elegoo Mars 4 Ultra
- Slicer:  Lychee (Free)

### Description of the bug

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service)
 ---> Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Method Destroy is not implemented on interface org.freedesktop.IBus.Service
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   --- End of inner exception stack trace ---
Category: Task
File: Door.goo  [Version: 0] [Class: GooFile]

Machine date time: 15/01/2024 12:11:04
    UTC date time: 15/01/2024 12:11:04
```

### How to reproduce

1. Open UVTools `./UVtools_linux-x64_v4.0.6.AppImage`
2. File -> Open, select `Door.goo`
3. Click Open
4. Error message pops up

### Files

The sliced file: https://drive.google.com/file/d/1EyqFCxsl3mM6iEgorLop1nnart93ViMf/view?usp=sharing

**Comment by sn4k3** [comment]
Duplicated of #803
