### ISSUE TITLE
UVtools crashed due an unexpected application error.

### ISSUE THREAD

**Issue by samsadatidds** [sn4k3/UVtools#844]
### System

```Text
UVtools v4.2.4 X64
Operative system: Microsoft Windows 10.0.19045 X64
Processor: Intel(R) Core(TM) i5-7500T CPU @ 2.70GHz
Processor cores: 4
Memory RAM: 8.83 / 15.96 GB
Runtime: win10-x64
Framework: .NET 6.0.27
AvaloniaUI: 11.0.7
OpenCV: 4.8.1

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 100% (Primary) (On this)
    WA: 1920 x 1040    UA: 1920 x 1040

Path:       C:\Users\Dr. Sam Sadati\Desktop\UV Tools\
Executable: C:\Users\Dr. Sam Sadati\Desktop\UV Tools\UVtools.exe
Loaded file: UVtools_demo_file.sl1s [Version: 0] [Class: SL1File]

General configuration for OpenCV 4.8.1 =====================================
  Version control:               4.8.1-255-gbb5bf05043

  Platform:
    Timestamp:                   2023-10-17T22:29:49Z
    Host:                        Windows 10.0.22000 AMD64
    CMake:                       3.23.0
    CMake generator:             Visual Studio 17 2022
    CMake build tool:            C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe
    MSVC:                        1937
    Configuration:               Debug Release MinSizeRel RelWithDebInfo

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                11
    C++ Compiler:                C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe  (ver 19.37.32825.0)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /wd4819 /MP  /MD /O2 /Ob2 /DNDEBUG 
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /wd4819 /MP  /MDd /Zi /Ob0 /Od /RTC1 
    C Compiler:                  C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP   /MD /O2 /Ob2 /DNDEBUG 
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP /MDd /Zi /Ob0 /Od /RTC1 
    Linker flags (Release):      /machine:x64  /INCREMENTAL:NO 
    Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL 
    ccache:                      NO
    Precompiled headers:         YES
    Extra dependencies:          comctl32 gdi32 ole32 setupapi ws2_32
    3rdparty dependencies:       ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf zlib

  OpenCV modules:
    To be built:                 core highgui imgcodecs imgproc ts videoio
    Disabled:                    dnn features2d flann gapi java ml photo python_bindings_generator python_tests video world
    Disabled by dependency:      calib3d objdetect stitching
    Unavailable:                 python2 python3
    Applications:                perf_tests
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI:                           WIN32UI
    Win32 UI:                    YES
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.2.13)
    JPEG:                        build-libjpeg-turbo (ver 2.1.3-62)
      SIMD Support Request:      YES
      SIMD Support:              NO
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.37)
    TIFF:                        build (ver 42 - 4.2.0)
    JPEG 2000:                   build (ver 2.5.0)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    DC1394:                      NO
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.134.100)
      avformat:                  YES (58.76.100)
      avutil:                    YES (56.70.100)
      swscale:                   YES (5.9.100)
      avresample:                YES (4.0.0)
    GStreamer:                   NO
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:                      YES

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Eigen:                       YES (ver 3.4.0)
    Custom HAL:                  NO
    Protobuf:                    build (3.19.1)
    Flatbuffers:                 builtin/3rdparty (23.5.9)

  OpenCL:                        YES (NVD3D11)
    Include path:                G:/bb/cv_pro_no_contrib/build/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python (for build):            C:/python-virt/python37/python.exe

  Java:                          
    ant:                         NO
    Java:                        YES (ver 1.8.0.202)
    JNI:                         C:/Program Files/Microsoft/jdk-11.0.16.101-hotspot/include C:/Program Files/Microsoft/jdk-11.0.16.101-hotspot/include/win32 C:/Program Files/Microsoft/jdk-11.0.16.101-hotspot/include
    Java wrappers:               NO
    Java tests:                  NO

  Install to:                    G:/bb/cv_pro_no_contrib/build/build_x86_64/install
-----------------------------------------------------------------


Loaded Assemblies:
01: System.Private.CoreLib, Version=6.0.0.0
02: UVtools, Version=4.2.4.0
03: System.Runtime, Version=6.0.0.0
04: Avalonia.Controls, Version=11.0.7.0
05: UVtools.Core, Version=4.2.4.0
06: System.Linq, Version=6.0.0.0
07: System.ObjectModel, Version=6.0.0.0
08: System.Drawing.Primitives, Version=6.0.0.0
09: System.Collections, Version=6.0.0.0
10: Avalonia.Base, Version=11.0.7.0
11: Avalonia.Skia, Version=11.0.7.0
12: Avalonia.Win32, Version=11.0.7.0
13: MicroCom.Runtime, Version=0.11.0.0
14: System.Collections.Concurrent, Version=6.0.0.0
15: System.Runtime.InteropServices, Version=6.0.0.0
16: System.Numerics.Vectors, Version=6.0.0.0
17: Avalonia.Native, Version=11.0.7.0
18: Avalonia.X11, Version=11.0.7.0
19: Projektanker.Icons.Avalonia, Version=9.1.1.0
20: netstandard, Version=2.1.0.0
21: Projektanker.Icons.Avalonia.FontAwesome, Version=9.1.1.0
22: Projektanker.Icons.Avalonia.MaterialDesign, Version=9.1.1.0
23: Avalonia.Desktop, Version=11.0.7.0
24: Avalonia.Fonts.Inter, Version=11.0.7.0
25: Avalonia.OpenGL, Version=11.0.7.0
26: System.ComponentModel.Primitives, Version=6.0.0.0
27: System.Threading, Version=6.0.0.0
28: System.Private.Uri, Version=6.0.0.0
29: SkiaSharp, Version=2.88.0.0
30: System.Runtime.InteropServices.RuntimeInformation, Version=6.0.0.0
31: Microsoft.Win32.Primitives, Version=6.0.0.0
32: System.ComponentModel, Version=6.0.0.0
33: System.Drawing.Common, Version=6.0.0.0
34: System.Threading.Thread, Version=6.0.0.0
35: Avalonia.MicroCom, Version=11.0.7.0
36: Avalonia.Markup.Xaml, Version=11.0.7.0
37: System.ComponentModel.TypeConverter, Version=6.0.0.0
38: UVtools.AvaloniaControls, Version=3.0.3.0
39: Avalonia.Themes.Fluent, Version=11.0.7.0
40: Avalonia.Dialogs, Version=11.0.7.0
41: Avalonia.Controls.ColorPicker, Version=11.0.7.0
42: Avalonia.Controls.DataGrid, Version=11.0.7.0
43: HarfBuzzSharp, Version=1.0.0.0
44: Emgu.CV, Version=4.8.1.5350
45: System.Memory, Version=6.0.0.0
46: System.Diagnostics.TraceSource, Version=6.0.0.0
47: System.Runtime.CompilerServices.Unsafe, Version=6.0.0.0
48: Avalonia.Markup, Version=11.0.7.0
49: System.Text.Json, Version=8.0.0.0
50: System.Text.Encodings.Web, Version=8.0.0.0
51: System.Text.Encoding.Extensions, Version=6.0.0.0
52: System.Runtime.Intrinsics, Version=6.0.0.0
53: System.Text.RegularExpressions, Version=6.0.0.0
54: System.Net.Http, Version=6.0.0.0
55: System.Net.Primitives, Version=6.0.0.0
56: BinarySerializer, Version=8.6.4.1
57: System.Threading.Tasks, Version=6.0.0.0
58: System.Diagnostics.Tracing, Version=6.0.0.0
59: System.IO, Version=6.0.0.0
60: System.Diagnostics.DiagnosticSource, Version=6.0.0.0
61: System.Text.Encoding, Version=6.0.0.0
62: System.Net.Security, Version=6.0.0.0
63: System.Security.Cryptography.X509Certificates, Version=6.0.0.0
64: System.Reflection.TypeExtensions, Version=6.0.0.0
65: System.Reflection, Version=6.0.0.0
66: System.Reflection.Extensions, Version=6.0.0.0
67: System.Linq.Expressions, Version=6.0.0.0
68: System.Reflection.Emit.ILGeneration, Version=6.0.0.0
69: System.Reflection.Emit.Lightweight, Version=6.0.0.0
70: System.Reflection.Primitives, Version=6.0.0.0
71: Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0
72: System.Net.Sockets, Version=6.0.0.0
73: System.Runtime.Extensions, Version=6.0.0.0
74: System.Threading.Overlapped, Version=6.0.0.0
75: System.Net.NameResolution, Version=6.0.0.0
76: System.Threading.ThreadPool, Version=6.0.0.0
77: System.IO.Compression.ZipFile, Version=6.0.0.0
78: System.IO.Compression, Version=6.0.0.0
79: System.Threading.Tasks.Parallel, Version=6.0.0.0
80: K4os.Compression.LZ4, Version=1.3.6.0
81: System.Security.Cryptography.Primitives, Version=6.0.0.0
82: System.Collections.NonGeneric, Version=6.0.0.0
83: System.Security.Principal.Windows, Version=6.0.0.0
84: System.Security.Claims, Version=6.0.0.0
85: System.Security.Cryptography.Encoding, Version=6.0.0.0
86: CommunityToolkit.HighPerformance, Version=8.2.0.0
87: System.IO.FileSystem.DriveInfo, Version=6.0.0.0
88: Microsoft.Win32.Registry, Version=6.0.0.0
```

### Printer and Slicer

- Printer: Phrozen Sonic Mini 4K
- Slicer: Chitubox

### Description of the bug

When opening the file on UV Tools (latest version), the Phrozen Sonic Mini 4K test file, the system crashes:
System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Decimal.DecCalc.VarDecFromR4(Single input, DecCalc& result)
   at System.Decimal.op_Explicit(Single value)
   at UVtools.Core.FileFormats.FileFormat.RefreshPrintParametersModifiersValues() in UVtools.Core\FileFormats\FileFormat.cs:line 4916
   at UVtools.Core.Operations.OperationEditParameters.InitWithSlicerFile() in UVtools.Core\Operations\OperationEditParameters.cs:line 163
   at UVtools.Core.Operations.Operation.set_SlicerFile(FileFormat value) in UVtools.Core\Operations\Operation.cs:line 84
   at UVtools.UI.MainWindow.ProcessFile(String fileName, FileDecodeType fileDecodeType, UInt32 actualLayer) in UVtools.UI\MainWindow.axaml.cs:line 1673
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore()
   at Avalonia.Threading.DispatcherOperation.Execute()
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job)
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore(Boolean fromExplicitBackgroundProcessingCallback)
   at Avalonia.Threading.Dispatcher.Signaled()
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode)
   at UVtools.UI.Program.Main(String[] args) in UVtools.UI\Program.cs:line 173
Category: Application
File: _Phrozen_test_Sonic_Mighty_4K.ctb  [Version: 4] [Class: ChituboxFile]

Machine date time: 3/5/2024 3:20:28 PM
    UTC date time: 3/5/2024 8:20:28 PM

### How to reproduce

Got to Open File, open the test file Phrozen Sonic Mini 4k test file

**Comment by sn4k3** [comment]
Attach the test file

**Comment by sn4k3** [comment]
No response
