### ISSUE TITLE
[Bug] UVTool freezing up when attempting prep file for new printer

### ISSUE THREAD

**Issue by c4box** [sn4k3/UVtools#883]
### System

```Text
UVtools v4.3.2 X64
Operative system: Microsoft Windows 10.0.22631 X64
Graphic card: 
Processor: Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
Processor cores: 8
Memory RAM: 2.96 / 7.84 GB
Runtime: win10-x64
Framework: .NET 6.0.29
AvaloniaUI: 11.0.10
OpenCV: 4.8.1

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: dreadpod_doorhinge.goo [Version: 0] [Class: GooFile]
```

### Printer and Slicer

- Printer: Elegoo Saturn 3 Ultra
- Slicer: Lychee

### Description of the bug

System.AggregateException: One or more errors occurred. (OpenCV: Failed to allocate 45028542 bytes) (OpenCV: Failed to allocate 53104635 bytes) (OpenCV: Failed to allocate 58982400 bytes) (OpenCV: Failed to allocate 220006492 bytes) (OpenCV: Failed to allocate 58380556 bytes) (OpenCV: Failed to allocate 58982400 bytes) (OpenCV: Failed to allocate 58982400 bytes) (OpenCV: Failed to allocate 55033659 bytes) (OpenCV: Failed to allocate 48944547 bytes)
 ---> Emgu.CV.Util.CvException: OpenCV: Failed to allocate 45028542 bytes
   at Emgu.CV.CvInvoke.cveFindContours(IntPtr image, IntPtr contours, IntPtr hierarchy, RetrType mode, ChainApproxMethod method, Point& offset)
   at Emgu.CV.CvInvoke.FindContours(IInputOutputArray image, IOutputArray contours, IOutputArray hierarchy, RetrType mode, ChainApproxMethod method, Point offset)
   at UVtools.Core.Extensions.EmguExtensions.FindContours(IInputOutputArray mat, Int32[,]& hierarchy, RetrType mode, ChainApproxMethod method, Point offset) in UVtools.Core\Extensions\EmguExtensions.cs:line 2256
   at UVtools.Core.Managers.IssueManager.<>c__DisplayClass18_2.<DetectIssues>b__9(Int64 layerIndexInt) in UVtools.Core\Managers\IssueManager.cs:line 651
   at System.Threading.Tasks.Parallel.<>c__DisplayClass20_0`1.<ForWorker64>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.<>c__DisplayClass20_0`1.<ForWorker64>b__1(RangeWorker& currentWorker, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
   at System.Threading.Tasks.TaskReplicator.Replica.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
   at System.Threading.Tasks.Parallel.ForWorker64[TLocal](Int64 fromInclusive, Int64 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
   at System.Threading.Tasks.Parallel.ForWorker64[TLocal](Int64 fromInclusive, Int64 toExclusive, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Func`4 bodyWithLocal, Func`1 localInit, Action`1 localFinally)
   at System.Threading.Tasks.Parallel.For(Int64 fromInclusive, Int64 toExclusive, ParallelOptions parallelOptions, Action`1 body)
   at UVtools.Core.Managers.IssueManager.DetectIssues(IssuesDetectionConfiguration config, OperationProgress progress) in UVtools.Core\Managers\IssueManager.cs:line 237
   at UVtools.UI.MainWindow.<>c__DisplayClass191_0.<ComputeIssues>b__0() in UVtools.UI\MainWindow.Issues.cs:line 609

### How to reproduce

1. Open UVTool,
2. Open file,
3. attempt to detect errors,
4. Error (after about 10-15 min of loading)

**Comment by sn4k3** [comment]
This is a RAM problem. Either upgrade your RAM, increase SWAP or allocate less UVtools threads in settings (Under Tasks).
