### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Francois-le-francais-dev** [sn4k3/UVtools#895]
### System

```Text
UVtools v4.3.2 X64
Operative system: Microsoft Windows 10.0.19045 X64
Graphic card: 
Processor: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
Processor cores: 12
Memory RAM: 7.65 / 15.81 GB
Runtime: win10-x64
Framework: .NET 6.0.29
AvaloniaUI: 11.0.10
OpenCV: 4.8.1

Path:       C:\Program Files\UVtools\
Executable: C:\Program Files\UVtools\UVtools.exe
Loaded file: P65Cx1_essai3.ctb [Version: 5] [Class: CTBEncryptedFile]
```

### Printer and Slicer

- Printer: 
- Slicer: 

### Description of the bug

export layers to Gif always crashes.
message :
System.IO.FileNotFoundException: Could not load file or assembly 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Le fichier spécifié est introuvable.
File name: 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at UVtools.Core.Operations.OperationLayerExportGif.ExecuteInternally(OperationProgress progress) in UVtools.Core\Operations\OperationLayerExportGif.cs:line 279
   at UVtools.Core.Operations.Operation.Execute(OperationProgress progress) in UVtools.Core\Operations\Operation.cs:line 790
   at UVtools.UI.MainWindow.<>c__DisplayClass111_0.<RunOperation>b__0() in UVtools.UI\MainWindow.axaml.cs:line 2421

### How to reproduce

1/ open any file or create one.
2/ export layers to Gif

**Comment by sn4k3** [comment]
It work on my system. Can you try to reinstall UVtools?
