### ISSUE TITLE
[Crash] System.Threading.Tasks.TaskCanceledException: A task was canceled.

### ISSUE THREAD

**Issue by trebory6** [sn4k3/UVtools#945]
### System

```Text
UVtools v4.4.3 X64
Operative system: Linux 6.11.9-200.fsync.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC TKG Mon Nov 18 06:46:57 UTC 2024 X64
Processor: AMD Ryzen 5 5600X 6-Core Processor
Processor cores: 12
Memory RAM: 25.49 / 31.26 GB
Runtime: nobara.40-x64
Framework: .NET 6.0.33
AvaloniaUI: 11.1.3
OpenCV: 4.9.0

Path:       /tmp/.mount_UVtoolxaNJYY/usr/bin/
Executable: /tmp/.mount_UVtoolxaNJYY/usr/bin/UVtools
```

### Printer and Slicer

- Printer: Elegoo Saturn 4 Ultra
- Slicer: Lychee Slicer 7.1.206

### Description of the bug

```
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Avalonia.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at Avalonia.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at Avalonia.Threading.Dispatcher.Send(SendOrPostCallback action, Object arg, Nullable`1 priority)
   at Avalonia.Threading.AvaloniaSynchronizationContext.Send(SendOrPostCallback d, Object state)
   at Tmds.DBus.Protocol.DBusConnection.Observer.Emit(Exception exception)
   at Tmds.DBus.Protocol.DBusConnection.Observer.Dispose(Exception exception, Boolean removeObserver)
   at Tmds.DBus.Protocol.DBusConnection.Dispose()
   at Tmds.DBus.Protocol.Connection.Disconnect(Exception disconnectReason, DBusConnection trigger)
   at Tmds.DBus.Protocol.DBusConnection.HandleMessages(Exception exception, Message message)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
Category: Non-UI
File: marker_smooth_engraved.goo  [Version: 0] [Class: GooFile]

Machine date time: 11/30/2024 10:17:27AM
    UTC date time: 11/30/2024 6:17:27PM
```

### How to reproduce

Honestly I just open a file from Lychee Slicer, and it hangs at 100% or close to 100% of "Gathering Bounds"
![Screenshot_20241130_102625](https://github.com/user-attachments/assets/a56ac538-8966-4789-b9ef-c045a56af98d)

### Files

[LycheeSlicer Files.zip](https://github.com/user-attachments/files/17966378/LycheeSlicer.Files.zip)

**Comment by sn4k3** [comment]
Can you reproduce again and while it does can you monitor your RAM using the system tools?
