### ISSUE TITLE
[Crash] System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.AppMenu.Registrar was not provided by any .service files)

### ISSUE THREAD

**Issue by nARN** [sn4k3/UVtools#964]
### System

```Text
UVtools v5.0.2 X64
Operative system: Ubuntu 24.04.1 LTS X64
Processor: Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
Processor cores: 16
Memory RAM: 20.79 / 125.73 GB
Runtime: linux-x64
Framework: .NET 9.0.0
AvaloniaUI: 11.2.3
OpenCV: 4.9.0

Path:       /tmp/.mount_uvtoolV1z0pR/usr/bin/
Executable: /tmp/.mount_uvtoolV1z0pR/usr/bin/UVtools
```

### Description of the bug

```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.AppMenu.Registrar was not provided by any .service files)
 ---> Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name com.canonical.AppMenu.Registrar was not provided by any .service files
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   --- End of inner exception stack trace ---
Category: Task
File: 1200prc_0.05mm.encrypted.ctb  [Version: 5] [Class: CTBEncryptedFile]

Machine date time: 20/12/2024 14:51:51
    UTC date time: 20/12/2024 14:51:51
```

### How to reproduce

I struggle to reproduce it, so suspect it may be some sort of a race. When I got this exception I had just reloaded a file and went straight into "Edit print parameters". It works fine now, but on DBus I can still see calls to `com.canonical.AppMenu.Registrar` and errors in response:
```
method call time=1734709363.187768 sender=:1.302 -> destination=com.canonical.AppMenu.Registrar serial=295 path=/com/canonical/AppMenu/Registrar; interface=com.canonical.AppMenu.Registrar; member=RegisterWindow
   uint32 41943155
   object path "/net/avaloniaui/dbusmenu/1032ada03730481484f5810ae4363f30"
error time=1734709363.187791 sender=org.freedesktop.DBus -> destination=:1.302 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=295
   string "The name com.canonical.AppMenu.Registrar was not provided by any .service files"
```

so I'm suspecting that the problem is that for some reason the exception was not caught at that time.

**Comment by sn4k3** [comment]
This comes from UI Framework, and other more have this problem: https://github.com/sn4k3/UVtools/issues?q=DBus
I don't know how to resolve it as it come from external source.
I'm gona ask to Avalonia...

**Comment by diefans** [comment]
for me this errors occurs since I use version 5.0.2...

**Comment by sn4k3** [comment]
Because v5 uses latest avalonia. If you revert to latest v4 it won't trigger this error.

**Comment by JoveToo** [comment]
It's really not rare with UVTools.

**Comment by Eisenknochen** [comment]
same  problem here (Using Linux Mint)

**Comment by sn4k3** [comment]
Is this fixed with latest release?

**Comment by JKBert** [comment]
Nope. I've just tested (Linux Devuan).

**Comment by sn4k3** [comment]
Dam, I tested on VM and works ok. Ubuntu as OP using. 
What is the most easy way to reproduce this?

**Comment by DodoidOfficial** [comment]
I can confirm I am also running into this on Debian Testing (Trixie) w/ KDE. What seems to trigger it most consistently is to attempt to hover over the stats in the bottom bar (e.g. Wait Time). The tooltip will flash up a couple of times (but is seemingly empty?), and UVtools usually crashes after a few seconds of this.

**Comment by sn4k3** [comment]
Check last version

**Comment by DodoidOfficial** [comment]
This now appears to work for me, both in the release version and building from source. The contents of the tooltip still are not visible, and the tooltip still disappears immediately after appearing, but it no longer seems to crash for me.

**Comment by sn4k3** [comment]
Yes, bug still there, is just ignored

https://github.com/user-attachments/assets/9cdcb6a8-8126-4088-a424-6b2e953120e3

**Comment by JKBert** [comment]
Tiago Conceição a écrit :
> Yes, bug still there, is just ignored
>
> https://github.com/user-attachments/assets/9cdcb6a8-8126-4088-a424-6b2e953120e3

	I have rebuilt UVtools from scratch this morning. 5.0.8 crashes as
older releases with the same error.

	Best regards,

	JB

**Comment by sn4k3** [comment]
> I have rebuilt UVtools from scratch this morning. 5.0.8 crashes as
> older releases with the same error.
> 
> 	Best regards,
> 
> 	JB

Can you post the error? For it to show it must be slight different, as I'm doing a message check

**Comment by JKBert** [comment]
> > I have rebuilt UVtools from scratch this morning. 5.0.8 crashes as
> > older releases with the same error.
> > Best regards,
> > JB
> 
> Can you post the error? For it to show it must be slight different, as I'm doing a message check

Hello,

I have done some tests. Here is a "standard" error message:
```
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. (org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/com/canonical/AppMenu/Registrar”)
 ---> Tmds.DBus.Protocol.DBusException: org.freedesktop.DBus.Error.UnknownMethod: Object does not exist at path “/com/canonical/AppMenu/Registrar”
   at Tmds.DBus.Protocol.DBusConnection.MyValueTaskSource`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at Tmds.DBus.Protocol.DBusConnection.CallMethodAsync(MessageBuffer message)
   at Tmds.DBus.Protocol.Connection.CallMethodAsync(MessageBuffer message)
   --- End of inner exception stack trace ---
Category: Task
File: UVtools_demo_file.sl1s  [Version: 0] [Class: SL1File]

Machine date time: 23/03/2025 14:08:41
    UTC date time: 23/03/2025 13:08:41
```
All information about configuration:
```
UVtools v5.0.8 X64
Operative system: Devuan GNU/Linux 6 (excalibur/ceres) X64
Processor: Intel(R) Core(TM) i9-10900F CPU @ 2.80GHz
Processor cores: 20
Memory RAM: 21.34 / 31.25 GB
Runtime: linux-x64
Framework: .NET 9.0.2
AvaloniaUI: 11.2.5
OpenCV: 4.10.0

Sreens, resolution, working area, usable area:
1: 1920 x 1080 @ 100% (Primary) (On this)
    WA: 1920 x 1080    UA: 1920 x 1080
2: 1920 x 1080 @ 100%
    WA: 1920 x 1080    UA: 1920 x 1080

Path:       /home/bertrand/git/UVtools/artifacts/publish/UVtools_linux-x64_v5.0.8/
Executable: /home/bertrand/git/UVtools/artifacts/publish/UVtools_linux-x64_v5.0.8/UVtools

General configuration for OpenCV 4.10.0 =====================================
  Version control:               3.4.2-10289-g3beff6e6c5

  Platform:
    Timestamp:                   2025-01-18T05:18:45Z
    Host:                        Linux 6.8.0-51-generic x86_64
    CMake:                       3.28.3
    CMake generator:             Unix Makefiles
    CMake build tool:            /usr/bin/gmake
    Configuration:               Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3
      requested:                 SSE3
    Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      SSE4_1 (13 files):         + SSSE3 SSE4_1
      SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
      FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
      AVX (3 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
      AVX2 (25 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
      AVX512_SKX (2 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      NO
    C++ standard:                17
    C++ Compiler:                /usr/bin/c++  (ver 13.3.0)
    C++ flags (Release):         -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -DNDEBUG  -DNDEBUG
    C++ flags (Debug):           -fsigned-char -W -Wall -Wreturn-type -Wnon-virtual-dtor -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wuninitialized -Wsuggest-override -Wno-delete-non-virtual-dtor -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -fvisibility-inlines-hidden -g  -O0 -DDEBUG -D_DEBUG
    C Compiler:                  /usr/bin/cc
    C flags (Release):           -fsigned-char -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -O3 -DNDEBUG  -DNDEBUG
    C flags (Debug):             -fsigned-char -W -Wall -Wreturn-type -Waddress -Wsequence-point -Wformat -Wformat-security -Wmissing-declarations -Wmissing-prototypes -Wstrict-prototypes -Wundef -Winit-self -Wpointer-arith -Wshadow -Wuninitialized -Wno-comment -Wimplicit-fallthrough=3 -Wno-strict-overflow -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -ffunction-sections -fdata-sections  -msse -msse2 -msse3 -fvisibility=hidden -g  -O0 -DDEBUG -D_DEBUG
    Linker flags (Release):      -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined  
    Linker flags (Debug):        -Wl,--exclude-libs,libippicv.a -Wl,--exclude-libs,libippiw.a   -Wl,--gc-sections -Wl,--as-needed -Wl,--no-undefined  
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:          dl m pthread rt
    3rdparty dependencies:       ittnotify libjpeg-turbo libwebp libpng libtiff libopenjp2 IlmImf zlib ippiw ippicv

  OpenCV modules:
    To be built:                 core highgui imgcodecs imgproc
    Disabled:                    dnn features2d flann gapi ml photo video videoio world
    Disabled by dependency:      calib3d objdetect stitching
    Unavailable:                 java python2 python3 ts
    Applications:                -
    Documentation:               NO
    Non-free algorithms:         NO

  GUI:                           NONE
    GTK+:                        NO
    VTK support:                 NO

  Media I/O: 
    ZLib:                        build (ver 1.3.1)
    JPEG:                        build-libjpeg-turbo (ver 3.0.3-70)
      SIMD Support Request:      YES
      SIMD Support:              NO
    WEBP:                        build (ver encoder: 0x020f)
    PNG:                         build (ver 1.6.43)
      SIMD Support Request:      YES
      SIMD Support:              YES (Intel SSE)
    TIFF:                        build (ver 42 - 4.6.0)
    JPEG 2000:                   build (ver 2.5.0)
    OpenEXR:                     build (ver 2.3.0)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:

  Parallel framework:            pthreads

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2021.11.0 [2021.11.0]
           at:                   /home/tiago/Desktop/emgucv/platforms/ubuntu/24.04/build/opencv/3rdparty/ippicv/ippicv_lnx/icv
    Intel IPP IW:                sources (2021.11.0)
              at:                /home/tiago/Desktop/emgucv/platforms/ubuntu/24.04/build/opencv/3rdparty/ippicv/ippicv_lnx/iw
    VA:                          NO
    Lapack:                      NO
    Custom HAL:                  NO
    Flatbuffers:                 builtin/3rdparty (23.5.9)

  OpenCL:                        YES (no extra features)
    Include path:                /home/tiago/Desktop/emgucv/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python (for build):            /usr/bin/python3

  Install to:                    /home/tiago/Desktop/emgucv/platforms/ubuntu/24.04/build/install
-----------------------------------------------------------------


Loaded Assemblies:
01: System.Private.CoreLib, Version=9.0.0.0
02: UVtools, Version=5.0.8.0
03: System.Runtime, Version=9.0.0.0
04: UVtools.Core, Version=5.0.8.0
05: System.Linq, Version=9.0.0.0
06: System.ObjectModel, Version=9.0.0.0
07: System.Drawing.Primitives, Version=9.0.0.0
08: System.Collections, Version=9.0.0.0
09: Avalonia.Controls, Version=11.2.5.0
10: Avalonia.Base, Version=11.2.5.0
11: Avalonia.Native, Version=11.2.5.0
12: MicroCom.Runtime, Version=0.11.0.0
13: System.Collections.Concurrent, Version=9.0.0.0
14: System.Runtime.InteropServices, Version=9.0.0.0
15: Avalonia.Skia, Version=11.2.5.0
16: Avalonia.Win32, Version=11.2.5.0
17: System.Numerics.Vectors, Version=9.0.0.0
18: Avalonia.X11, Version=11.2.5.0
19: Projektanker.Icons.Avalonia, Version=9.6.1.0
20: netstandard, Version=2.1.0.0
21: Projektanker.Icons.Avalonia.FontAwesome, Version=9.6.1.0
22: Projektanker.Icons.Avalonia.MaterialDesign, Version=9.6.1.0
23: Avalonia.Desktop, Version=11.2.5.0
24: Avalonia.Fonts.Inter, Version=11.2.5.0
25: Avalonia.OpenGL, Version=11.2.5.0
26: System.ComponentModel.Primitives, Version=9.0.0.0
27: System.Threading, Version=9.0.0.0
28: System.Private.Uri, Version=9.0.0.0
29: SkiaSharp, Version=2.88.0.0
30: Avalonia.FreeDesktop, Version=11.2.5.0
31: System.Threading.Thread, Version=9.0.0.0
32: System.Memory, Version=9.0.0.0
33: System.Diagnostics.TraceSource, Version=9.0.0.0
34: Avalonia.Vulkan, Version=11.2.5.0
35: Tmds.DBus.Protocol, Version=0.20.0.0
36: System.IO.Pipelines, Version=9.0.0.0
37: System.Net.Primitives, Version=9.0.0.0
38: System.Net.Sockets, Version=9.0.0.0
39: Microsoft.Win32.Primitives, Version=9.0.0.0
40: System.Diagnostics.Tracing, Version=9.0.0.0
41: System.Threading.ThreadPool, Version=9.0.0.0
42: System.Diagnostics.DiagnosticSource, Version=9.0.0.0
43: System.Threading.Channels, Version=9.0.0.0
44: Avalonia.Markup.Xaml, Version=11.2.5.0
45: System.ComponentModel, Version=9.0.0.0
46: Avalonia.Markup, Version=11.2.5.0
47: System.ComponentModel.TypeConverter, Version=9.0.0.0
48: UVtools.AvaloniaControls, Version=4.0.4.0
49: Avalonia.Themes.Fluent, Version=11.2.5.0
50: Avalonia.Dialogs, Version=11.2.5.0
51: Avalonia.Controls.ColorPicker, Version=11.2.5.0
52: Avalonia.Controls.DataGrid, Version=11.2.5.0
53: System.Xml.XmlSerializer, Version=9.0.0.0
54: System.Private.Xml, Version=9.0.0.0
55: System.Collections.NonGeneric, Version=9.0.0.0
56: System.Text.Encoding.Extensions, Version=9.0.0.0
57: System.Runtime.Loader, Version=9.0.0.0
58: System.Collections.Specialized, Version=9.0.0.0
59: System.Xml.ReaderWriter, Version=9.0.0.0
60: System.Reflection.Emit.ILGeneration, Version=9.0.0.0
61: System.Reflection.Emit, Version=9.0.0.0
62: Microsoft.GeneratedCode, Version=1.0.0.0
63: System.Reflection.Primitives, Version=9.0.0.0
64: System.Text.RegularExpressions, Version=9.0.0.0
65: HarfBuzzSharp, Version=1.0.0.0
66: System.Diagnostics.Process, Version=9.0.0.0
67: System.IO.Pipes, Version=9.0.0.0
68: Emgu.CV, Version=4.10.0.5680
69: System.Web.HttpUtility, Version=9.0.0.0
70: System.Text.Json, Version=9.0.0.0
71: System.Text.Encodings.Web, Version=9.0.0.0
72: System.Runtime.Intrinsics, Version=9.0.0.0
73: Markdown.Avalonia, Version=11.0.2.0
74: BinarySerializer, Version=8.6.4.1
75: System.Threading.Tasks, Version=9.0.0.0
76: System.IO, Version=9.0.0.0
77: System.Text.Encoding, Version=9.0.0.0
78: System.Reflection.TypeExtensions, Version=9.0.0.0
79: System.Reflection, Version=9.0.0.0
80: System.Reflection.Extensions, Version=9.0.0.0
81: System.Runtime.InteropServices.RuntimeInformation, Version=9.0.0.0
82: System.Linq.Expressions, Version=9.0.0.0
83: System.Reflection.Emit.Lightweight, Version=9.0.0.0
84: Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0
85: System.Runtime.Extensions, Version=9.0.0.0
86: System.ComponentModel.Annotations, Version=9.0.0.0

```

**Comment by sn4k3** [comment]
@JKBert The error you getting is not included in my bypass, your is `UnknownMethod` while the current bypass is `ServiceUnknown`.
I can include both in next release.

**Comment by JKBert** [comment]
I have added a quick and dirty patch to ignore this error in UVtools.UI/Program.cs and UVtools now runs as expected.

```
    private static void HandleUnhandledException(string category, Exception ex)
    { 
        ErrorLog.AppendLine($"Fatal {category} Error", ex.ToString());

        if (category == "Task")
        {
            if (ex.Message.Contains("org.freedesktop.DBus.Error.ServiceUnknown")) return; 
            if (ex.Message.Contains("org.freedesktop.DBus.Error.UnknownMethod")) return;
        }
```
